spring:
  cloud:
    gateway:
      discovery,locator:
        enabled: true
        IowerCaseServiceld: true
      routes:
        - id: organization~service
          uri: lb://organization-service

      predicates:
      - Path=/organization/**
      filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}